# Google Cloud Build configuration for building Android APK/AAB
# This builds your Expo app natively without using EAS

steps:
  # Step 1: Install Node.js dependencies
  - name: "node:20"
    entrypoint: "npm"
    args: ["install"]
    id: "install-dependencies"

  # Step 2: Run Expo prebuild to generate native Android code
  - name: "node:20"
    entrypoint: "npx"
    args: ["expo", "prebuild", "--platform", "android", "--no-install"]
    id: "expo-prebuild"
    waitFor: ["install-dependencies"]

  # Step 3: Retrieve keystore from Secret Manager (for release builds)
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "${_BUILD_TYPE}" = "release" ]; then
          echo "Retrieving keystore from Secret Manager..."
          gcloud secrets versions access latest --secret=ANDROID_KEYSTORE > /workspace/android/app/release.keystore
          echo "MYAPP_UPLOAD_STORE_FILE=release.keystore" >> /workspace/android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_ALIAS=$(gcloud secrets versions access latest --secret=KEY_ALIAS)" >> /workspace/android/gradle.properties
          echo "MYAPP_UPLOAD_STORE_PASSWORD=$(gcloud secrets versions access latest --secret=KEYSTORE_PASSWORD)" >> /workspace/android/gradle.properties
          echo "MYAPP_UPLOAD_KEY_PASSWORD=$(gcloud secrets versions access latest --secret=KEY_PASSWORD)" >> /workspace/android/gradle.properties
        fi
    id: "setup-keystore"
    waitFor: ["expo-prebuild"]

  # Step 4: Build Android APK or AAB using Gradle
  - name: "mingc/android-build-box:latest"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        cd android
        chmod +x ./gradlew

        if [ "${_BUILD_TYPE}" = "debug" ]; then
          echo "Building debug APK..."
          ./gradlew assembleDebug
          cp app/build/outputs/apk/debug/app-debug.apk /workspace/app-debug.apk
        elif [ "${_BUILD_TYPE}" = "release-apk" ]; then
          echo "Building release APK..."
          ./gradlew assembleRelease
          cp app/build/outputs/apk/release/app-release.apk /workspace/app-release.apk
        else
          echo "Building release AAB..."
          ./gradlew bundleRelease
          cp app/build/outputs/bundle/release/app-release.aab /workspace/app-release.aab
        fi
    id: "build-android"
    waitFor: ["setup-keystore"]

# Store build artifacts in Cloud Storage
artifacts:
  objects:
    location: "gs://${_BUCKET_NAME}/builds/${BUILD_ID}"
    paths:
      - "app-*.apk"
      - "app-*.aab"

# Substitution variables (can be overridden when triggering build)
substitutions:
  _BUILD_TYPE: "debug" # Options: debug, release-apk, release
  _BUCKET_NAME: "fpr-builds" # Change this to your bucket name

# Build configuration
options:
  machineType: "E2_HIGHCPU_8" # Use a powerful machine for faster builds
  logging: CLOUD_LOGGING_ONLY

# Timeout: Android builds can take a while
timeout: "1800s" # 30 minutes
